### ISSUE TITLE
Implementation option

### ISSUE THREAD

**Issue by peterpt** [streamaserver/streama#1004] opened 2020-07-19 20:10 UTC
I was wondering if it is possible to add a search box in "File Manager" page to look for raw files uploaded before .
When you have more than 300 titles on server it takes a lot to find the right tab where that specific file is so it can be deleted .

**Comment by dularion** [comment] 2020-07-20 07:00
Can you append a screenshot of the search box that you are referring to?

**Comment by peterpt** [comment] 2020-07-20 17:52
a Search box to look for files on "file Manager" would be nice , it takes a lot of time to look into all tabs bellow to find a previous uploaded file .
![streamasb](https://user-images.githubusercontent.com/7487321/87969508-2f07f580-caba-11ea-8df1-77e54095d7c5.jpg)

**Comment by LukeSteward** [comment] 2021-02-21 13:55
Duplicate of #1004

**Closed by LukeSteward** 2021-02-21 13:55 UTC
Labels: Enhancement
