### ISSUE TITLE
Register System | Display Edits 

### ISSUE THREAD

**Issue by playdream** [streamaserver/streama#658] opened 2018-08-19 14:17 UTC
is it possible to have users register instead of me creating users?

is possible to add some display edits 

example in settings add background for main display and few ccs edits or area to add custom css and html?

**Comment by Jeronimo95** [comment] 2018-08-20 05:15
Please make one post per feature request, this makes them easier to track and is clearly stated in the issue template. User registration is duplicate of #298.

**Closed by Jeronimo95** 2018-08-20 05:15 UTC
