### ISSUE TITLE
File manager not working

### ISSUE THREAD

**Issue by d000000h** [streamaserver/streama#302] opened 2017-02-16 13:29 UTC
The file manager doesnt seem to be working at the moment at least for me

Running on Ubuntu

i dont use mysql to store data mostly default settings

here is gif to show the problem

![streama](https://cloud.githubusercontent.com/assets/10897164/23023085/271a3ef4-f454-11e6-9061-cdbda86f7814.gif)

**Comment by robsonolivesa** [comment] 2017-02-17 20:30
i have the same problem. Im running in Unbuntu too.

**Comment by dularion** [comment] 2017-02-19 20:52
will check it out

**Comment by CSCG** [comment] 2017-04-09 02:07
This isn't fixed; still occurring on Ubuntu 16.04 as of 4/8/2017

**Comment by 2knarf** [comment] 2017-10-10 15:59
Still have the problem both under Oracle 8 and OpenJDK 8

**Comment by dularion** [comment] 2017-12-08 20:25
I can't reproduce this problem... The file manager works for me. Can you give me access to your installation so i can debug?

**Comment by LukeSteward** [comment] 2021-02-06 15:11
Are you still having this issue in the latest version or can we close this issue?

**Comment by LukeSteward** [comment] 2021-02-21 14:39
Due to inactivity surrounding this topic I am closing it. If this is not solved please reopen the issue.

**Closed by LukeSteward** 2021-02-21 14:39 UTC
Labels: Bug, Can't reproduce
